global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "url-shortener-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:9090", "api:9090"]

  - job_name: "grafana-alloy"
    static_configs:
      - targets: ["alloy:12345"]
