// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
WHERE ($1::text IS NULL OR (
    email ILIKE '%' || $1::text || '%' OR
    full_name ILIKE '%' || $1::text || '%'
))
`

func (q *Queries) CountAllUsers(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSystemStats = `-- name: GetSystemStats :one
SELECT
    (SELECT COUNT(*) FROM users) AS total_users,
    (SELECT COUNT(*) FROM short_urls WHERE deleted_at IS NULL) AS total_urls,
    (SELECT COUNT(*) FROM short_urls WHERE deleted_at IS NULL AND is_active = TRUE) AS total_active_urls,
    (SELECT COALESCE(SUM(click_count), 0)::bigint FROM short_urls) AS total_clicks
`

type GetSystemStatsRow struct {
	TotalUsers      int64 `json:"total_users"`
	TotalUrls       int64 `json:"total_urls"`
	TotalActiveUrls int64 `json:"total_active_urls"`
	TotalClicks     int64 `json:"total_clicks"`
}

func (q *Queries) GetSystemStats(ctx context.Context) (GetSystemStatsRow, error) {
	row := q.db.QueryRow(ctx, getSystemStats)
	var i GetSystemStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalUrls,
		&i.TotalActiveUrls,
		&i.TotalClicks,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, email, full_name, role, is_suspended, created_at, updated_at
FROM users
WHERE ($1::text IS NULL OR (
    email ILIKE '%' || $1::text || '%' OR
    full_name ILIKE '%' || $1::text || '%'
))
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAllUsersParams struct {
	Search    pgtype.Text `json:"search"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

type ListAllUsersRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	FullName    string    `json:"full_name"`
	Role        string    `json:"role"`
	IsSuspended bool      `json:"is_suspended"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.Search, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUsersRow{}
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.IsSuspended,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSuspended = `-- name: SetUserSuspended :one
UPDATE users
SET is_suspended = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, email, full_name, role, is_suspended, created_at, updated_at
`

type SetUserSuspendedParams struct {
	ID          uuid.UUID `json:"id"`
	IsSuspended bool      `json:"is_suspended"`
}

type SetUserSuspendedRow struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	FullName    string    `json:"full_name"`
	Role        string    `json:"role"`
	IsSuspended bool      `json:"is_suspended"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) SetUserSuspended(ctx context.Context, arg SetUserSuspendedParams) (SetUserSuspendedRow, error) {
	row := q.db.QueryRow(ctx, setUserSuspended, arg.ID, arg.IsSuspended)
	var i SetUserSuspendedRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.IsSuspended,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
