// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getURLAnalyticsSummary = `-- name: GetURLAnalyticsSummary :one
SELECT 
    COUNT(*)::bigint AS total_clicks,
    COUNT(DISTINCT ip_address)::bigint AS unique_visitors
FROM url_analytics
WHERE url_id = $1
`

type GetURLAnalyticsSummaryRow struct {
	TotalClicks    int64 `json:"total_clicks"`
	UniqueVisitors int64 `json:"unique_visitors"`
}

func (q *Queries) GetURLAnalyticsSummary(ctx context.Context, urlID uuid.UUID) (GetURLAnalyticsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getURLAnalyticsSummary, urlID)
	var i GetURLAnalyticsSummaryRow
	err := row.Scan(&i.TotalClicks, &i.UniqueVisitors)
	return i, err
}

const listRecentClicksByUrlID = `-- name: ListRecentClicksByUrlID :many
SELECT id, url_id, ip_address, user_agent, referrer, device_type, country, clicked_at FROM url_analytics
WHERE url_id = $1
ORDER BY clicked_at DESC
LIMIT $2 OFFSET $3
`

type ListRecentClicksByUrlIDParams struct {
	UrlID  uuid.UUID `json:"url_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRecentClicksByUrlID(ctx context.Context, arg ListRecentClicksByUrlIDParams) ([]UrlAnalytic, error) {
	rows, err := q.db.Query(ctx, listRecentClicksByUrlID, arg.UrlID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UrlAnalytic{}
	for rows.Next() {
		var i UrlAnalytic
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referrer,
			&i.DeviceType,
			&i.Country,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordClick = `-- name: RecordClick :one
INSERT INTO url_analytics (
    url_id,
    ip_address,
    user_agent,
    referrer,
    device_type,
    country
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, url_id, ip_address, user_agent, referrer, device_type, country, clicked_at
`

type RecordClickParams struct {
	UrlID      uuid.UUID `json:"url_id"`
	IpAddress  string    `json:"ip_address"`
	UserAgent  string    `json:"user_agent"`
	Referrer   string    `json:"referrer"`
	DeviceType string    `json:"device_type"`
	Country    string    `json:"country"`
}

func (q *Queries) RecordClick(ctx context.Context, arg RecordClickParams) (UrlAnalytic, error) {
	row := q.db.QueryRow(ctx, recordClick,
		arg.UrlID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referrer,
		arg.DeviceType,
		arg.Country,
	)
	var i UrlAnalytic
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referrer,
		&i.DeviceType,
		&i.Country,
		&i.ClickedAt,
	)
	return i, err
}
