// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)
FROM audit_logs
WHERE ($1::text IS NULL OR (
    actor_email ILIKE '%' || $1::text || '%' OR
    action ILIKE '%' || $1::text || '%' OR
    resource ILIKE '%' || $1::text || '%'
))
`

func (q *Queries) CountAuditLogs(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_id, actor_email, action, resource, resource_id, payload, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, actor_id, actor_email, action, resource, resource_id, payload, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorEmail string      `json:"actor_email"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID string      `json:"resource_id"`
	Payload    string      `json:"payload"`
	IpAddress  string      `json:"ip_address"`
	UserAgent  string      `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorID,
		arg.ActorEmail,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Payload,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorEmail,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Payload,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentAuditLogs = `-- name: GetRecentAuditLogs :many
SELECT id, actor_id, actor_email, action, resource, resource_id, payload, ip_address, user_agent, created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getRecentAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Payload,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, actor_email, action, resource, resource_id, payload, ip_address, user_agent, created_at
FROM audit_logs
WHERE ($1::text IS NULL OR (
    actor_email ILIKE '%' || $1::text || '%' OR
    action ILIKE '%' || $1::text || '%' OR
    resource ILIKE '%' || $1::text || '%'
))
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsParams struct {
	Search    pgtype.Text `json:"search"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Search, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Payload,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
