// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
)

const getSystemConfigByKey = `-- name: GetSystemConfigByKey :one
SELECT key, value, description, updated_at
FROM system_configs
WHERE key = $1
`

func (q *Queries) GetSystemConfigByKey(ctx context.Context, key string) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, getSystemConfigByKey, key)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemConfigs = `-- name: ListSystemConfigs :many
SELECT key, value, description, updated_at
FROM system_configs
ORDER BY key ASC
`

func (q *Queries) ListSystemConfigs(ctx context.Context) ([]SystemConfig, error) {
	rows, err := q.db.Query(ctx, listSystemConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemConfig{}
	for rows.Next() {
		var i SystemConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemConfig = `-- name: UpsertSystemConfig :one
INSERT INTO system_configs (key, value, description, updated_at)
VALUES (
    $1::text,
    $2::jsonb,
    $3::text,
    NOW()
)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, description = COALESCE(NULLIF(EXCLUDED.description, ''), system_configs.description), updated_at = NOW()
RETURNING key, value, description, updated_at
`

type UpsertSystemConfigParams struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
}

func (q *Queries) UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, upsertSystemConfig, arg.Key, arg.Value, arg.Description)
	var i SystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}
