// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menus.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const createNavigationMenu = `-- name: CreateNavigationMenu :one
INSERT INTO navigation_menus (parent_id, title, path, icon, order_index, is_active, is_external, is_group, badge_text, permission_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, parent_id, title, path, icon, order_index, is_active, is_external, is_group, badge_text, permission_code, created_at, updated_at
`

type CreateNavigationMenuParams struct {
	ParentID       pgtype.UUID `json:"parent_id"`
	Title          string      `json:"title"`
	Path           string      `json:"path"`
	Icon           string      `json:"icon"`
	OrderIndex     int32       `json:"order_index"`
	IsActive       bool        `json:"is_active"`
	IsExternal     bool        `json:"is_external"`
	IsGroup        bool        `json:"is_group"`
	BadgeText      string      `json:"badge_text"`
	PermissionCode pgtype.Text `json:"permission_code"`
}

type CreateNavigationMenuRow struct {
	ID             uuid.UUID   `json:"id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Title          string      `json:"title"`
	Path           string      `json:"path"`
	Icon           string      `json:"icon"`
	OrderIndex     int32       `json:"order_index"`
	IsActive       bool        `json:"is_active"`
	IsExternal     bool        `json:"is_external"`
	IsGroup        bool        `json:"is_group"`
	BadgeText      string      `json:"badge_text"`
	PermissionCode pgtype.Text `json:"permission_code"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) CreateNavigationMenu(ctx context.Context, arg CreateNavigationMenuParams) (CreateNavigationMenuRow, error) {
	row := q.db.QueryRow(ctx, createNavigationMenu,
		arg.ParentID,
		arg.Title,
		arg.Path,
		arg.Icon,
		arg.OrderIndex,
		arg.IsActive,
		arg.IsExternal,
		arg.IsGroup,
		arg.BadgeText,
		arg.PermissionCode,
	)
	var i CreateNavigationMenuRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Path,
		&i.Icon,
		&i.OrderIndex,
		&i.IsActive,
		&i.IsExternal,
		&i.IsGroup,
		&i.BadgeText,
		&i.PermissionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNavigationMenu = `-- name: DeleteNavigationMenu :exec
DELETE FROM navigation_menus
WHERE id = $1
`

func (q *Queries) DeleteNavigationMenu(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNavigationMenu, id)
	return err
}

const getNavigationMenuByID = `-- name: GetNavigationMenuByID :one
SELECT id, parent_id, title, path, icon, order_index, is_active, is_external, is_group, badge_text, permission_code, created_at, updated_at
FROM navigation_menus
WHERE id = $1
`

type GetNavigationMenuByIDRow struct {
	ID             uuid.UUID   `json:"id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Title          string      `json:"title"`
	Path           string      `json:"path"`
	Icon           string      `json:"icon"`
	OrderIndex     int32       `json:"order_index"`
	IsActive       bool        `json:"is_active"`
	IsExternal     bool        `json:"is_external"`
	IsGroup        bool        `json:"is_group"`
	BadgeText      string      `json:"badge_text"`
	PermissionCode pgtype.Text `json:"permission_code"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) GetNavigationMenuByID(ctx context.Context, id uuid.UUID) (GetNavigationMenuByIDRow, error) {
	row := q.db.QueryRow(ctx, getNavigationMenuByID, id)
	var i GetNavigationMenuByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Path,
		&i.Icon,
		&i.OrderIndex,
		&i.IsActive,
		&i.IsExternal,
		&i.IsGroup,
		&i.BadgeText,
		&i.PermissionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNavigationMenus = `-- name: ListNavigationMenus :many
SELECT id, parent_id, title, path, icon, order_index, is_active, is_external, is_group, badge_text, permission_code, created_at, updated_at
FROM navigation_menus
ORDER BY order_index ASC, created_at ASC
`

type ListNavigationMenusRow struct {
	ID             uuid.UUID   `json:"id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Title          string      `json:"title"`
	Path           string      `json:"path"`
	Icon           string      `json:"icon"`
	OrderIndex     int32       `json:"order_index"`
	IsActive       bool        `json:"is_active"`
	IsExternal     bool        `json:"is_external"`
	IsGroup        bool        `json:"is_group"`
	BadgeText      string      `json:"badge_text"`
	PermissionCode pgtype.Text `json:"permission_code"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) ListNavigationMenus(ctx context.Context) ([]ListNavigationMenusRow, error) {
	rows, err := q.db.Query(ctx, listNavigationMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavigationMenusRow{}
	for rows.Next() {
		var i ListNavigationMenusRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Path,
			&i.Icon,
			&i.OrderIndex,
			&i.IsActive,
			&i.IsExternal,
			&i.IsGroup,
			&i.BadgeText,
			&i.PermissionCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuOrderIndex = `-- name: UpdateMenuOrderIndex :exec
UPDATE navigation_menus
SET order_index = $2, parent_id = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateMenuOrderIndexParams struct {
	ID         uuid.UUID   `json:"id"`
	OrderIndex int32       `json:"order_index"`
	ParentID   pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateMenuOrderIndex(ctx context.Context, arg UpdateMenuOrderIndexParams) error {
	_, err := q.db.Exec(ctx, updateMenuOrderIndex, arg.ID, arg.OrderIndex, arg.ParentID)
	return err
}

const updateNavigationMenu = `-- name: UpdateNavigationMenu :one
UPDATE navigation_menus
SET parent_id = $2, title = $3, path = $4, icon = $5, order_index = $6, is_active = $7, is_external = $8, is_group = $9, badge_text = $10, permission_code = $11, updated_at = NOW()
WHERE id = $1
RETURNING id, parent_id, title, path, icon, order_index, is_active, is_external, is_group, badge_text, permission_code, created_at, updated_at
`

type UpdateNavigationMenuParams struct {
	ID             uuid.UUID   `json:"id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Title          string      `json:"title"`
	Path           string      `json:"path"`
	Icon           string      `json:"icon"`
	OrderIndex     int32       `json:"order_index"`
	IsActive       bool        `json:"is_active"`
	IsExternal     bool        `json:"is_external"`
	IsGroup        bool        `json:"is_group"`
	BadgeText      string      `json:"badge_text"`
	PermissionCode pgtype.Text `json:"permission_code"`
}

type UpdateNavigationMenuRow struct {
	ID             uuid.UUID   `json:"id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Title          string      `json:"title"`
	Path           string      `json:"path"`
	Icon           string      `json:"icon"`
	OrderIndex     int32       `json:"order_index"`
	IsActive       bool        `json:"is_active"`
	IsExternal     bool        `json:"is_external"`
	IsGroup        bool        `json:"is_group"`
	BadgeText      string      `json:"badge_text"`
	PermissionCode pgtype.Text `json:"permission_code"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateNavigationMenu(ctx context.Context, arg UpdateNavigationMenuParams) (UpdateNavigationMenuRow, error) {
	row := q.db.QueryRow(ctx, updateNavigationMenu,
		arg.ID,
		arg.ParentID,
		arg.Title,
		arg.Path,
		arg.Icon,
		arg.OrderIndex,
		arg.IsActive,
		arg.IsExternal,
		arg.IsGroup,
		arg.BadgeText,
		arg.PermissionCode,
	)
	var i UpdateNavigationMenuRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Path,
		&i.Icon,
		&i.OrderIndex,
		&i.IsActive,
		&i.IsExternal,
		&i.IsGroup,
		&i.BadgeText,
		&i.PermissionCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
