// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type AuditLog struct {
	ID         uuid.UUID   `json:"id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorEmail string      `json:"actor_email"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID string      `json:"resource_id"`
	Payload    string      `json:"payload"`
	IpAddress  string      `json:"ip_address"`
	UserAgent  string      `json:"user_agent"`
	CreatedAt  time.Time   `json:"created_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Payload       string             `json:"payload"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID         uuid.UUID `json:"role_id"`
	PermissionCode string    `json:"permission_code"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type ShortUrl struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	Title       string             `json:"title"`
	IsActive    bool               `json:"is_active"`
	ClickCount  int64              `json:"click_count"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type SystemConfig struct {
	Key         string    `json:"key"`
	Value       string    `json:"value"`
	Description string    `json:"description"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UrlAnalytic struct {
	ID         uuid.UUID `json:"id"`
	UrlID      uuid.UUID `json:"url_id"`
	IpAddress  string    `json:"ip_address"`
	UserAgent  string    `json:"user_agent"`
	Referrer   string    `json:"referrer"`
	DeviceType string    `json:"device_type"`
	Country    string    `json:"country"`
	ClickedAt  time.Time `json:"clicked_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	GoogleID     pgtype.Text `json:"google_id"`
	AvatarUrl    string      `json:"avatar_url"`
	FullName     string      `json:"full_name"`
	Role         string      `json:"role"`
	IsSuspended  bool        `json:"is_suspended"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
