// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type ShortUrl struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	Title       string             `json:"title"`
	IsActive    bool               `json:"is_active"`
	ClickCount  int64              `json:"click_count"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type UrlAnalytic struct {
	ID         uuid.UUID `json:"id"`
	UrlID      uuid.UUID `json:"url_id"`
	IpAddress  string    `json:"ip_address"`
	UserAgent  string    `json:"user_agent"`
	Referrer   string    `json:"referrer"`
	DeviceType string    `json:"device_type"`
	Country    string    `json:"country"`
	ClickedAt  time.Time `json:"clicked_at"`
}

type User struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	GoogleID     pgtype.Text `json:"google_id"`
	AvatarUrl    string      `json:"avatar_url"`
	FullName     string      `json:"full_name"`
	Role         string      `json:"role"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}
