// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const clearReadNotifications = `-- name: ClearReadNotifications :exec
DELETE FROM notifications
WHERE user_id = $1 AND is_read = TRUE
`

func (q *Queries) ClearReadNotifications(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearReadNotifications, userID)
	return err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserNotifications = `-- name: CountUserNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1
  AND ($2::boolean IS NULL OR ($2::boolean = TRUE AND is_read = FALSE))
  AND ($3::text IS NULL OR type = $3::text)
  AND ($4::text IS NULL OR (
    title ILIKE '%' || $4::text || '%' OR
    message ILIKE '%' || $4::text || '%'
  ))
`

type CountUserNotificationsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	UnreadOnly pgtype.Bool `json:"unread_only"`
	Type       pgtype.Text `json:"type"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) CountUserNotifications(ctx context.Context, arg CountUserNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.Type,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    title,
    message,
    type
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, title, message, type, is_read, created_at
`

type CreateNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Title   string    `json:"title"`
	Message string    `json:"message"`
	Type    string    `json:"type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Type,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, title, message, type, is_read, created_at
FROM notifications
WHERE user_id = $1
  AND ($2::boolean IS NULL OR ($2::boolean = TRUE AND is_read = FALSE))
  AND ($3::text IS NULL OR type = $3::text)
  AND ($4::text IS NULL OR (
    title ILIKE '%' || $4::text || '%' OR
    message ILIKE '%' || $4::text || '%'
  ))
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListUserNotificationsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	UnreadOnly pgtype.Bool `json:"unread_only"`
	Type       pgtype.Text `json:"type"`
	Search     pgtype.Text `json:"search"`
	OffsetVal  int32       `json:"offset_val"`
	LimitVal   int32       `json:"limit_val"`
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUserNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.Type,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = TRUE
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, message, type, is_read, created_at
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
