// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUserShortURLs(ctx context.Context, arg CountUserShortURLsParams) (int64, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShortURL(ctx context.Context, arg CreateShortURLParams) (ShortUrl, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateExpiredURLs(ctx context.Context) (pgconn.CommandTag, error)
	DeleteShortURL(ctx context.Context, arg DeleteShortURLParams) error
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetShortURLByCode(ctx context.Context, shortCode string) (ShortUrl, error)
	GetShortURLByID(ctx context.Context, id uuid.UUID) (ShortUrl, error)
	GetURLAnalyticsSummary(ctx context.Context, urlID uuid.UUID) (GetURLAnalyticsSummaryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserCountryBreakdown(ctx context.Context, userID pgtype.UUID) ([]GetUserCountryBreakdownRow, error)
	GetUserDashboardSummary(ctx context.Context, userID pgtype.UUID) (GetUserDashboardSummaryRow, error)
	GetUserDeviceBreakdown(ctx context.Context, userID pgtype.UUID) ([]GetUserDeviceBreakdownRow, error)
	GetUserTopReferrers(ctx context.Context, arg GetUserTopReferrersParams) ([]GetUserTopReferrersRow, error)
	IncrementClickCount(ctx context.Context, id uuid.UUID) error
	ListRecentClicksByUrlID(ctx context.Context, arg ListRecentClicksByUrlIDParams) ([]UrlAnalytic, error)
	ListUserShortURLs(ctx context.Context, arg ListUserShortURLsParams) ([]ShortUrl, error)
	MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error
	RecordClick(ctx context.Context, arg RecordClickParams) (UrlAnalytic, error)
	RestoreShortURL(ctx context.Context, arg RestoreShortURLParams) (ShortUrl, error)
	RevokeSession(ctx context.Context, id uuid.UUID) error
	UpdateShortURL(ctx context.Context, arg UpdateShortURLParams) (ShortUrl, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
