// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_code)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID         uuid.UUID `json:"role_id"`
	PermissionCode string    `json:"permission_code"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionCode)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, roleID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, name, display_name, description, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, display_name, description, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	TenantID    *uuid.UUID `json:"tenant_id"`
	Name        string     `json:"name"`
	DisplayName string     `json:"display_name"`
	Description string     `json:"description"`
	IsSystem    bool       `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.TenantID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, display_name, description, is_system, created_at, updated_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, tenant_id, name, display_name, description, is_system, created_at, updated_at
FROM roles
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT permission_code
FROM role_permissions
WHERE role_id = $1
ORDER BY permission_code ASC
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_code string
		if err := rows.Scan(&permission_code); err != nil {
			return nil, err
		}
		items = append(items, permission_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantRoleByName = `-- name: GetTenantRoleByName :one
SELECT id, tenant_id, name, display_name, description, is_system, created_at, updated_at
FROM roles
WHERE name = $1 AND (tenant_id = $2 OR tenant_id IS NULL)
ORDER BY tenant_id DESC LIMIT 1
`

type GetTenantRoleByNameParams struct {
	Name     string     `json:"name"`
	TenantID *uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTenantRoleByName(ctx context.Context, arg GetTenantRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getTenantRoleByName, arg.Name, arg.TenantID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTenantPermissions = `-- name: GetUserTenantPermissions :many
SELECT DISTINCT rp.permission_code
FROM role_permissions rp
JOIN roles r ON r.id = rp.role_id
JOIN tenant_memberships tm ON tm.role = r.name
WHERE tm.user_id = $1 AND tm.tenant_id = $2
`

type GetUserTenantPermissionsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetUserTenantPermissions(ctx context.Context, arg GetUserTenantPermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserTenantPermissions, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_code string
		if err := rows.Scan(&permission_code); err != nil {
			return nil, err
		}
		items = append(items, permission_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, display_name, description, is_system, created_at, updated_at
FROM roles
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRoles = `-- name: ListSystemRoles :many
SELECT id, tenant_id, name, display_name, description, is_system, created_at, updated_at
FROM roles
WHERE tenant_id IS NULL
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListSystemRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listSystemRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantRoles = `-- name: ListTenantRoles :many
SELECT id, tenant_id, name, display_name, description, is_system, created_at, updated_at
FROM roles
WHERE tenant_id = $1 OR tenant_id IS NULL
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListTenantRoles(ctx context.Context, tenantID *uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listTenantRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET display_name = $2, description = $3, updated_at = NOW()
WHERE id = $1 AND is_system = false
RETURNING id, tenant_id, name, display_name, description, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.DisplayName, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
