// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTenantMember = `-- name: AddTenantMember :one
INSERT INTO tenant_memberships (
    tenant_id,
    user_id,
    role
) VALUES (
    $1, $2, $3
)
ON CONFLICT (tenant_id, user_id) DO UPDATE SET
    role = EXCLUDED.role
RETURNING tenant_id, user_id, role, created_at
`

type AddTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, addTenantMember, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countAllTenantsAdmin = `-- name: CountAllTenantsAdmin :one
SELECT COUNT(*) FROM tenants t
WHERE ($1::text IS NULL OR (
    t.name ILIKE '%' || $1::text || '%' OR
    t.slug ILIKE '%' || $1::text || '%' OR
    t.join_code ILIKE '%' || $1::text || '%'
))
`

func (q *Queries) CountAllTenantsAdmin(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTenantsAdmin, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name,
    slug,
    join_code
) VALUES (
    $1, $2, $3
)
RETURNING id, name, slug, join_code, created_at, updated_at
`

type CreateTenantParams struct {
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	JoinCode string `json:"join_code"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug, arg.JoinCode)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenantAdmin = `-- name: DeleteTenantAdmin :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenantAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantAdmin, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, join_code, created_at, updated_at
FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByJoinCode = `-- name: GetTenantByJoinCode :one
SELECT id, name, slug, join_code, created_at, updated_at
FROM tenants
WHERE join_code = $1 LIMIT 1
`

func (q *Queries) GetTenantByJoinCode(ctx context.Context, joinCode string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByJoinCode, joinCode)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, join_code, created_at, updated_at
FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantMembership = `-- name: GetTenantMembership :one
SELECT tenant_id, user_id, role, created_at
FROM tenant_memberships
WHERE tenant_id = $1 AND user_id = $2 LIMIT 1
`

type GetTenantMembershipParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTenantMembership(ctx context.Context, arg GetTenantMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, getTenantMembership, arg.TenantID, arg.UserID)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAllTenantMemberships = `-- name: ListAllTenantMemberships :many
SELECT tenant_id, user_id, role, created_at
FROM tenant_memberships
`

func (q *Queries) ListAllTenantMemberships(ctx context.Context) ([]TenantMembership, error) {
	rows, err := q.db.Query(ctx, listAllTenantMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantMembership{}
	for rows.Next() {
		var i TenantMembership
		if err := rows.Scan(
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTenantsAdmin = `-- name: ListAllTenantsAdmin :many
SELECT t.id, t.name, t.slug, t.join_code, t.created_at, t.updated_at,
       COUNT(tm.user_id)::bigint AS member_count
FROM tenants t
LEFT JOIN tenant_memberships tm ON t.id = tm.tenant_id
WHERE ($1::text IS NULL OR (
    t.name ILIKE '%' || $1::text || '%' OR
    t.slug ILIKE '%' || $1::text || '%' OR
    t.join_code ILIKE '%' || $1::text || '%'
))
GROUP BY t.id
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $2
`

type ListAllTenantsAdminParams struct {
	Search    *string `json:"search"`
	OffsetVal int32   `json:"offset_val"`
	LimitVal  int32   `json:"limit_val"`
}

type ListAllTenantsAdminRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	JoinCode    string    `json:"join_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	MemberCount int64     `json:"member_count"`
}

func (q *Queries) ListAllTenantsAdmin(ctx context.Context, arg ListAllTenantsAdminParams) ([]ListAllTenantsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAllTenantsAdmin, arg.Search, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTenantsAdminRow{}
	for rows.Next() {
		var i ListAllTenantsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.JoinCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT u.id as user_id, u.email, u.full_name, u.avatar_url, tm.role, tm.created_at
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1
ORDER BY tm.created_at ASC
`

type ListTenantMembersRow struct {
	UserID    uuid.UUID `json:"user_id"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	AvatarUrl string    `json:"avatar_url"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListTenantMembers(ctx context.Context, tenantID uuid.UUID) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenants = `-- name: ListUserTenants :many
SELECT t.id, t.name, t.slug, t.join_code, tm.role, t.created_at, t.updated_at
FROM tenants t
JOIN tenant_memberships tm ON t.id = tm.tenant_id
WHERE tm.user_id = $1
ORDER BY t.created_at ASC
`

type ListUserTenantsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	JoinCode  string    `json:"join_code"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListUserTenants(ctx context.Context, userID uuid.UUID) ([]ListUserTenantsRow, error) {
	rows, err := q.db.Query(ctx, listUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTenantsRow{}
	for rows.Next() {
		var i ListUserTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.JoinCode,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateTenantJoinCode = `-- name: RegenerateTenantJoinCode :one
UPDATE tenants
SET join_code = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, join_code, created_at, updated_at
`

type RegenerateTenantJoinCodeParams struct {
	ID       uuid.UUID `json:"id"`
	JoinCode string    `json:"join_code"`
}

func (q *Queries) RegenerateTenantJoinCode(ctx context.Context, arg RegenerateTenantJoinCodeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, regenerateTenantJoinCode, arg.ID, arg.JoinCode)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeTenantMember = `-- name: RemoveTenantMember :exec
DELETE FROM tenant_memberships
WHERE tenant_id = $1 AND user_id = $2
`

type RemoveTenantMemberParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTenantMember(ctx context.Context, arg RemoveTenantMemberParams) error {
	_, err := q.db.Exec(ctx, removeTenantMember, arg.TenantID, arg.UserID)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = COALESCE($2::text, name),
    slug = COALESCE($3::text, slug),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, join_code, created_at, updated_at
`

type UpdateTenantParams struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
	Slug *string   `json:"slug"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.ID, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantMemberRole = `-- name: UpdateTenantMemberRole :one
UPDATE tenant_memberships
SET role = $3
WHERE tenant_id = $1 AND user_id = $2
RETURNING tenant_id, user_id, role, created_at
`

type UpdateTenantMemberRoleParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
}

func (q *Queries) UpdateTenantMemberRole(ctx context.Context, arg UpdateTenantMemberRoleParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, updateTenantMemberRole, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMembership
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
