// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserShortURLs = `-- name: CountUserShortURLs :one
SELECT COUNT(*) FROM short_urls
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR (
      title ILIKE '%' || $2::text || '%' OR
      short_code ILIKE '%' || $2::text || '%' OR
      original_url ILIKE '%' || $2::text || '%'
  ))
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
`

type CountUserShortURLsParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Search    pgtype.Text        `json:"search"`
	IsActive  pgtype.Bool        `json:"is_active"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

func (q *Queries) CountUserShortURLs(ctx context.Context, arg CountUserShortURLsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserShortURLs,
		arg.UserID,
		arg.Search,
		arg.IsActive,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShortURL = `-- name: CreateShortURL :one
INSERT INTO short_urls (
    user_id,
    short_code,
    original_url,
    title,
    is_active,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, short_code, original_url, title, is_active, click_count, expires_at, created_at, updated_at, deleted_at
`

type CreateShortURLParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ShortCode   string             `json:"short_code"`
	OriginalUrl string             `json:"original_url"`
	Title       string             `json:"title"`
	IsActive    bool               `json:"is_active"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, createShortURL,
		arg.UserID,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.Title,
		arg.IsActive,
		arg.ExpiresAt,
	)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Title,
		&i.IsActive,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateExpiredURLs = `-- name: DeactivateExpiredURLs :many
UPDATE short_urls
SET is_active = FALSE, updated_at = NOW()
WHERE is_active = TRUE AND deleted_at IS NULL AND expires_at IS NOT NULL AND expires_at < NOW()
RETURNING short_code
`

func (q *Queries) DeactivateExpiredURLs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, deactivateExpiredURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var short_code string
		if err := rows.Scan(&short_code); err != nil {
			return nil, err
		}
		items = append(items, short_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteShortURL = `-- name: DeleteShortURL :exec
UPDATE short_urls
SET deleted_at = NOW(), is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND (user_id = $2 OR $2 IS NULL) AND deleted_at IS NULL
`

type DeleteShortURLParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteShortURL(ctx context.Context, arg DeleteShortURLParams) error {
	_, err := q.db.Exec(ctx, deleteShortURL, arg.ID, arg.UserID)
	return err
}

const getShortURLByCode = `-- name: GetShortURLByCode :one
SELECT id, user_id, short_code, original_url, title, is_active, click_count, expires_at, created_at, updated_at, deleted_at FROM short_urls
WHERE short_code = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetShortURLByCode(ctx context.Context, shortCode string) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getShortURLByCode, shortCode)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Title,
		&i.IsActive,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getShortURLByID = `-- name: GetShortURLByID :one
SELECT id, user_id, short_code, original_url, title, is_active, click_count, expires_at, created_at, updated_at, deleted_at FROM short_urls
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetShortURLByID(ctx context.Context, id uuid.UUID) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getShortURLByID, id)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Title,
		&i.IsActive,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE short_urls
SET click_count = click_count + 1,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) IncrementClickCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementClickCount, id)
	return err
}

const listUserShortURLs = `-- name: ListUserShortURLs :many
SELECT id, user_id, short_code, original_url, title, is_active, click_count, expires_at, created_at, updated_at, deleted_at FROM short_urls
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR (
      title ILIKE '%' || $2::text || '%' OR
      short_code ILIKE '%' || $2::text || '%' OR
      original_url ILIKE '%' || $2::text || '%'
  ))
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at <= $5::timestamptz)
ORDER BY
  CASE WHEN $6::text = 'click_count_asc' THEN click_count END ASC,
  CASE WHEN $6::text = 'click_count_desc' THEN click_count END DESC,
  CASE WHEN $6::text = 'title_asc' THEN title END ASC,
  CASE WHEN $6::text = 'title_desc' THEN title END DESC,
  CASE WHEN $6::text = 'short_code_asc' THEN short_code END ASC,
  CASE WHEN $6::text = 'short_code_desc' THEN short_code END DESC,
  CASE WHEN $6::text = 'created_at_asc' THEN created_at END ASC,
  CASE WHEN $6::text = 'created_at_desc' OR $6::text IS NULL OR $6::text = '' THEN created_at END DESC
LIMIT $8 OFFSET $7
`

type ListUserShortURLsParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Search    pgtype.Text        `json:"search"`
	IsActive  pgtype.Bool        `json:"is_active"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	SortBy    string             `json:"sort_by"`
	OffsetVal int32              `json:"offset_val"`
	LimitVal  int32              `json:"limit_val"`
}

func (q *Queries) ListUserShortURLs(ctx context.Context, arg ListUserShortURLsParams) ([]ShortUrl, error) {
	rows, err := q.db.Query(ctx, listUserShortURLs,
		arg.UserID,
		arg.Search,
		arg.IsActive,
		arg.StartDate,
		arg.EndDate,
		arg.SortBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortUrl{}
	for rows.Next() {
		var i ShortUrl
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.Title,
			&i.IsActive,
			&i.ClickCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreShortURL = `-- name: RestoreShortURL :one
UPDATE short_urls
SET deleted_at = NULL, is_active = TRUE, updated_at = NOW()
WHERE id = $1 AND (user_id = $2 OR $2 IS NULL) AND deleted_at IS NOT NULL
RETURNING id, user_id, short_code, original_url, title, is_active, click_count, expires_at, created_at, updated_at, deleted_at
`

type RestoreShortURLParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RestoreShortURL(ctx context.Context, arg RestoreShortURLParams) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, restoreShortURL, arg.ID, arg.UserID)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Title,
		&i.IsActive,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateShortURL = `-- name: UpdateShortURL :one
UPDATE short_urls
SET
    title = COALESCE($2, title),
    original_url = COALESCE($3, original_url),
    is_active = COALESCE($4, is_active),
    expires_at = COALESCE($5, expires_at),
    updated_at = NOW()
WHERE id = $1 AND (user_id = $6 OR $6 IS NULL) AND deleted_at IS NULL
RETURNING id, user_id, short_code, original_url, title, is_active, click_count, expires_at, created_at, updated_at, deleted_at
`

type UpdateShortURLParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       pgtype.Text        `json:"title"`
	OriginalUrl pgtype.Text        `json:"original_url"`
	IsActive    pgtype.Bool        `json:"is_active"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpdateShortURL(ctx context.Context, arg UpdateShortURLParams) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, updateShortURL,
		arg.ID,
		arg.Title,
		arg.OriginalUrl,
		arg.IsActive,
		arg.ExpiresAt,
		arg.UserID,
	)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.Title,
		&i.IsActive,
		&i.ClickCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
