// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    full_name,
    role
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, password_hash, google_id, avatar_url, full_name, role, created_at, updated_at, is_suspended
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, google_id, avatar_url, full_name, role, created_at, updated_at, is_suspended FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, password_hash, google_id, avatar_url, full_name, role, created_at, updated_at, is_suspended FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, google_id, avatar_url, full_name, role, created_at, updated_at, is_suspended FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = COALESCE($2, full_name),
    password_hash = COALESCE($3, password_hash),
    avatar_url = COALESCE($4, avatar_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, google_id, avatar_url, full_name, role, created_at, updated_at, is_suspended
`

type UpdateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	FullName     pgtype.Text `json:"full_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.PasswordHash,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO users (
    email,
    google_id,
    avatar_url,
    full_name,
    role
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (email) DO UPDATE SET
    google_id = EXCLUDED.google_id,
    avatar_url = EXCLUDED.avatar_url,
    full_name = EXCLUDED.full_name,
    updated_at = NOW()
RETURNING id, email, password_hash, google_id, avatar_url, full_name, role, created_at, updated_at, is_suspended
`

type UpsertGoogleUserParams struct {
	Email     string      `json:"email"`
	GoogleID  pgtype.Text `json:"google_id"`
	AvatarUrl string      `json:"avatar_url"`
	FullName  string      `json:"full_name"`
	Role      string      `json:"role"`
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser,
		arg.Email,
		arg.GoogleID,
		arg.AvatarUrl,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.AvatarUrl,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsSuspended,
	)
	return i, err
}
